name: Publish package
on:
  workflow_dispatch:
    inputs:
      changes:
        description: Release changes
        default: List of changes.
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: "3.6"
    - name: Install poetry
      uses: dschep/install-poetry-action@v1.3
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: ${{ github.event.inputs.changes }}
        draft: false
        prerelease: false
    - name: Publish package
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry config pypi-token.pypi $PYPI_TOKEN
        poetry publish --build