name: Publish release
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: "3.6"
    - name: Install poetry
      uses: dschep/install-poetry-action@v1.3
    - name: Publish package
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry config pypi-token.pypi $PYPI_TOKEN
        poetry publish --build